[tool.black]
line-length = 100
target-version = ['py312']
exclude = '\\.(venv|git|migrations)'

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py312"
select = ["E", "F", "I", "UP", "B"]
ignore = []
exclude = ["app/db/migrations/*"]

[tool.pytest.ini_options]
addopts = "-q"
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.12"
