version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pmdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
