# Sample Fly.io config
app = "pm-api-sample"
primary_region = "iad"

[build]
  dockerfile = "infra/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    path = "/health"
